# Generated by Django 2.2.6 on 2021-03-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_time',
            field=models.CharField(default='', max_length=256),
        ),
    ]
