# Generated by Django 2.2.6 on 2021-03-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yob', '0002_course_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lesson_time',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='courses',
            field=models.ManyToManyField(blank=True, to='yob.Course'),
        ),
    ]
